<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <Version>2.0.0</Version>
	  <AssemblyVersion>2.0.0.0</AssemblyVersion>
	  <FileVersion>2.0.0.0</FileVersion>
	  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
	  <SelfContained>true</SelfContained>
	  <PublishSingleFile>true</PublishSingleFile>
	  <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>IronResolve_Installer_V0._9._6</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="33fb201a-3e5d-4117-9c4b-307d1da8da01.png" />
    <None Remove="Assets\logo.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\logo.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.8" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>